#service load balance
apiVersion: v1
kind: Service
metadata:
  name: configuration-service
spec:
  selector:
    app: configuration-app
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  