#service load balance
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
spec:
  selector:
    app: eureka-app
  type: LoadBalancer
  ports:
    - port: 8761
      targetPort: 8761
      protocol: TCP
