#service load balance
apiVersion: v1
kind: Service
metadata:
  name: licensing-service
spec:
  selector:
    app: licensing-app
  type: LoadBalancer
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
  